export const menus = [
  {
    id: "1",
    name: "Salad",
    image: "/menu_1.png",
  },
  {
    id: "2",
    name: "Rolls",
    image: "/menu_2.png",
  },
  {
    id: "3",
    name: "Deserts",
    image: "/menu_3.png",
  },
  {
    id: "4",
    name: "Sandwich",
    image: "/menu_4.png",
  },
  {
    id: "5",
    name: "Cake",
    image: "/menu_5.png",
  },
  {
    id: "6",
    name: "Pure Veg",
    image: "/menu_6.png",
  },
  {
    id: "7",
    name: "Pasta",
    image: "/menu_7.png",
  },
  {
    id: "8",
    name: "Noodles",
    image: "/menu_8.png",
  },
];

export const food_list = [
  {
    _id: "1",
    name: "Greek salad",
    image: "/food_1.png",
    price: 12,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Salad",
  },
  {
    _id: "2",
    name: "Veg salad",
    image: "/food_2.png",
    price: 18,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Salad",
  },
  {
    _id: "3",
    name: "Clover Salad",
    image: "/food_3.png",
    price: 16,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Salad",
  },
  {
    _id: "4",
    name: "Chicken Salad",
    image: "/food_4.png",
    price: 24,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Salad",
  },
  {
    _id: "5",
    name: "Lasagna Rolls",
    image: "/food_5.png",
    price: 14,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Rolls",
  },
  {
    _id: "6",
    name: "Peri Peri Rolls",
    image: "/food_6.png",
    price: 12,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Rolls",
  },
  {
    _id: "7",
    name: "Chicken Rolls",
    image: "/food_7.png",
    price: 20,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Rolls",
  },
  {
    _id: "8",
    name: "Veg Rolls",
    image: "/food_8.png",
    price: 15,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Rolls",
  },
  {
    _id: "9",
    name: "Ripple Ice Cream",
    image: "/food_9.png",
    price: 14,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Deserts",
  },
  {
    _id: "10",
    name: "Fruit Ice Cream",
    image: "/food_10.png",
    price: 22,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Deserts",
  },
  {
    _id: "11",
    name: "Jar Ice Cream",
    image: "/food_11.png",
    price: 10,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Deserts",
  },
  {
    _id: "12",
    name: "Vanilla Ice Cream",
    image: "/food_12.png",
    price: 12,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Deserts",
  },
  {
    _id: "13",
    name: "Chicken Sandwich",
    image: "/food_13.png",
    price: 12,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Sandwich",
  },
  {
    _id: "14",
    name: "Vegan Sandwich",
    image: "/food_14.png",
    price: 18,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Sandwich",
  },
  {
    _id: "15",
    name: "Grilled Sandwich",
    image: "/food_15.png",
    price: 16,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Sandwich",
  },
  {
    _id: "16",
    name: "Bread Sandwich",
    image: "/food_16.png",
    price: 24,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Sandwich",
  },
  {
    _id: "17",
    name: "Cup Cake",
    image: "/food_17.png",
    price: 14,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Cake",
  },
  {
    _id: "18",
    name: "Vegan Cake",
    image: "/food_18.png",
    price: 12,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Cake",
  },
  {
    _id: "19",
    name: "Butterscotch Cake",
    image: "/food_19.png",
    price: 20,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Cake",
  },
  {
    _id: "20",
    name: "Sliced Cake",
    image: "/food_20.png",
    price: 15,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Cake",
  },
  {
    _id: "21",
    name: "Garlic Mushroom",
    image: "/food_21.png",
    price: 14,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Pure Veg",
  },
  {
    _id: "22",
    name: "Fried Cauliflower",
    image: "/food_22.png",
    price: 22,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Pure Veg",
  },
  {
    _id: "23",
    name: "Mix Veg Pulao",
    image: "/food_23.png",
    price: 10,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Pure Veg",
  },
  {
    _id: "24",
    name: "Rice Zucchini",
    image: "/food_24.png",
    price: 12,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Pure Veg",
  },
  {
    _id: "25",
    name: "Cheese Pasta",
    image: "/food_25.png",
    price: 12,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Pasta",
  },
  {
    _id: "26",
    name: "Tomato Pasta",
    image: "/food_26.png",
    price: 18,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Pasta",
  },
  {
    _id: "27",
    name: "Creamy Pasta",
    image: "/food_27.png",
    price: 16,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Pasta",
  },
  {
    _id: "28",
    name: "Chicken Pasta",
    image: "/food_28.png",
    price: 24,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Pasta",
  },
  {
    _id: "29",
    name: "Butter Noodles",
    image: "/food_29.png",
    price: 14,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Noodles",
  },
  {
    _id: "30",
    name: "Veg Noodles",
    image: "/food_30.png",
    price: 12,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Noodles",
  },
  {
    _id: "31",
    name: "Somen Noodles",
    image: "/food_31.png",
    price: 20,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Noodles",
  },
  {
    _id: "32",
    name: "Cooked Noodles",
    image: "/food_32.png",
    price: 15,
    description:
      "Food provides essential nutrients for overall health and well-being",
    category: "Noodles",
  },
];

export const fosodDetails = [
  {
    _id: "1",
    name: "Greek Salad",
    image: "/food_1.png",
    price: 12,
    description:
      "A refreshing and classic salad with fresh vegetables and feta cheese, perfect for a light meal.",
    category: "Salad",
    flavorProfile: "Fresh, tangy, slightly salty",
    servingSize: "1 bowl (approx. 300g)",
    cookingStyle: "Chilled, no-cook",
    ingredients: [
      "Lettuce",
      "Tomatoes",
      "Cucumbers",
      "Olives",
      "Feta cheese",
      "Olive oil",
    ],
  },
  {
    _id: "2",
    name: "Veg Salad",
    image: "/food_2.png",
    price: 18,
    description:
      "A vibrant mix of fresh veggies that is both healthy and delicious.",
    category: "Salad",
    flavorProfile: "Crunchy and fresh with a hint of sweetness",
    servingSize: "1 bowl (approx. 300g)",
    cookingStyle: "Chilled, no-cook",
    ingredients: [
      "Lettuce",
      "Carrots",
      "Cucumbers",
      "Bell peppers",
      "Vinaigrette",
    ],
  },
  {
    _id: "3",
    name: "Clover Salad",
    image: "/food_3.png",
    price: 16,
    description: "A flavorful salad with fresh greens and a light dressing.",
    category: "Salad",
    flavorProfile: "Earthy and slightly sweet",
    servingSize: "1 bowl (approx. 300g)",
    cookingStyle: "Chilled, no-cook",
    ingredients: ["Mixed greens", "Radishes", "Carrots", "Light vinaigrette"],
  },
  {
    _id: "4",
    name: "Chicken Salad",
    image: "/food_4.png",
    price: 24,
    description:
      "A hearty salad with grilled chicken, perfect for a filling meal.",
    category: "Salad",
    flavorProfile: "Savory and slightly smoky",
    servingSize: "1 bowl (approx. 350g)",
    cookingStyle: "Grilled and chilled",
    ingredients: [
      "Grilled chicken",
      "Lettuce",
      "Cherry tomatoes",
      "Cucumbers",
      "Ranch dressing",
    ],
  },
  {
    _id: "5",
    name: "Lasagna Rolls",
    image: "/food_5.png",
    price: 14,
    description:
      "Savory lasagna rolled with cheese and herbs, baked to perfection.",
    category: "Rolls",
    flavorProfile: "Cheesy and hearty",
    servingSize: "2 rolls (approx. 250g)",
    cookingStyle: "Baked",
    ingredients: [
      "Lasagna sheets",
      "Ricotta cheese",
      "Spinach",
      "Tomato sauce",
      "Parmesan",
    ],
  },
  {
    _id: "6",
    name: "Peri Peri Rolls",
    image: "/food_6.png",
    price: 12,
    description:
      "Spicy rolls with a peri peri sauce, perfect for spice lovers.",
    category: "Rolls",
    flavorProfile: "Spicy and tangy",
    servingSize: "2 rolls (approx. 200g)",
    cookingStyle: "Baked",
    ingredients: [
      "Tortilla wraps",
      "Peri peri sauce",
      "Chicken",
      "Lettuce",
      "Cheese",
    ],
  },
  {
    _id: "7",
    name: "Chicken Rolls",
    image: "/food_7.png",
    price: 20,
    description:
      "Grilled chicken wrapped in a soft roll, served with fresh vegetables.",
    category: "Rolls",
    flavorProfile: "Savory and juicy",
    servingSize: "2 rolls (approx. 250g)",
    cookingStyle: "Grilled",
    ingredients: [
      "Chicken breast",
      "Tortilla wraps",
      "Lettuce",
      "Tomato",
      "Cheese",
    ],
  },
  {
    _id: "8",
    name: "Veg Rolls",
    image: "/food_8.png",
    price: 15,
    description: "Crunchy veggies wrapped in a soft roll with a hint of spice.",
    category: "Rolls",
    flavorProfile: "Crunchy and fresh",
    servingSize: "2 rolls (approx. 200g)",
    cookingStyle: "Baked",
    ingredients: [
      "Tortilla wraps",
      "Bell peppers",
      "Carrots",
      "Lettuce",
      "Chili sauce",
    ],
  },
  {
    _id: "9",
    name: "Ripple Ice Cream",
    image: "/food_9.png",
    price: 14,
    description: "Smooth and creamy ice cream with a ripple of fruity flavor.",
    category: "Deserts",
    flavorProfile: "Sweet and fruity",
    servingSize: "1 scoop (approx. 150g)",
    cookingStyle: "Frozen",
    ingredients: ["Milk", "Cream", "Fruit syrup", "Sugar"],
  },
  {
    _id: "10",
    name: "Fruit Ice Cream",
    image: "/food_10.png",
    price: 22,
    description: "Deliciously creamy ice cream with fresh fruit chunks.",
    category: "Deserts",
    flavorProfile: "Creamy and fruity",
    servingSize: "1 scoop (approx. 150g)",
    cookingStyle: "Frozen",
    ingredients: ["Milk", "Cream", "Mixed fruits", "Sugar"],
  },
  {
    _id: "11",
    name: "Jar Ice Cream",
    image: "/food_11.png",
    price: 10,
    description: "Ice cream served in a jar for easy enjoyment on the go.",
    category: "Deserts",
    flavorProfile: "Sweet and creamy",
    servingSize: "1 jar (approx. 200g)",
    cookingStyle: "Frozen",
    ingredients: ["Milk", "Cream", "Flavoring", "Sugar"],
  },
  {
    _id: "12",
    name: "Vanilla Ice Cream",
    image: "/food_12.png",
    price: 12,
    description: "Classic vanilla ice cream made with real vanilla beans.",
    category: "Deserts",
    flavorProfile: "Sweet and smooth",
    servingSize: "1 scoop (approx. 150g)",
    cookingStyle: "Frozen",
    ingredients: ["Milk", "Cream", "Vanilla beans", "Sugar"],
  },
  {
    _id: "13",
    name: "Chicken Sandwich",
    image: "/food_13.png",
    price: 12,
    description:
      "Grilled chicken sandwich with fresh vegetables and a tasty sauce.",
    category: "Sandwich",
    flavorProfile: "Savory and filling",
    servingSize: "1 sandwich (approx. 200g)",
    cookingStyle: "Grilled",
    ingredients: [
      "Grilled chicken",
      "Bread",
      "Lettuce",
      "Tomato",
      "Mayonnaise",
    ],
  },
  {
    _id: "14",
    name: "Vegan Sandwich",
    image: "/food_14.png",
    price: 18,
    description: "A healthy sandwich made with fresh veggies and vegan spread.",
    category: "Sandwich",
    flavorProfile: "Fresh and light",
    servingSize: "1 sandwich (approx. 200g)",
    cookingStyle: "No-cook",
    ingredients: [
      "Whole grain bread",
      "Avocado",
      "Lettuce",
      "Tomato",
      "Hummus",
    ],
  },
  {
    _id: "15",
    name: "Grilled Sandwich",
    image: "/food_15.png",
    price: 16,
    description: "A crispy grilled sandwich with melted cheese and veggies.",
    category: "Sandwich",
    flavorProfile: "Cheesy and crispy",
    servingSize: "1 sandwich (approx. 200g)",
    cookingStyle: "Grilled",
    ingredients: ["Bread", "Cheese", "Tomato", "Onion"],
  },
  {
    _id: "16",
    name: "Bread Sandwich",
    image: "/food_16.png",
    price: 24,
    description: "Simple bread sandwich with fresh ingredients.",
    category: "Sandwich",
    flavorProfile: "Simple and fresh",
    servingSize: "1 sandwich (approx. 200g)",
    cookingStyle: "No-cook",
    ingredients: ["Bread", "Butter", "Lettuce", "Tomato"],
  },
  {
    _id: "17",
    name: "Cup Cake",
    image: "/food_17.png",
    price: 14,
    description: "Soft and moist cupcake with a sweet frosting.",
    category: "Cake",
    flavorProfile: "Sweet and soft",
    servingSize: "1 cupcake (approx. 100g)",
    cookingStyle: "Baked",
    ingredients: ["Flour", "Sugar", "Butter", "Eggs", "Frosting"],
  },
  {
    _id: "18",
    name: "Vegan Cake",
    image: "/food_18.png",
    price: 12,
    description: "A delicious vegan cake made without dairy or eggs.",
    category: "Cake",
    flavorProfile: "Moist and sweet",
    servingSize: "1 slice (approx. 150g)",
    cookingStyle: "Baked",
    ingredients: [
      "Flour",
      "Sugar",
      "Coconut oil",
      "Baking powder",
      "Almond milk",
    ],
  },
];


export const foodDetails = [
  {
    _id: "1",
    name: "Greek Salad",
    image: "/food_1.png",
    price: 12,
    description:
      "A refreshing and classic salad with fresh vegetables and feta cheese, perfect for a light meal.",
    category: "Salad",
    flavor: "Fresh, tangy, slightly salty",
    servingSize: "1 bowl (approx. 300g)",
    cookingStyle: "Chilled, no-cook",
    ingredients: "Lettuce, Tomatoes, Cucumbers, Olives, Feta cheese, Olive oil",
  },
  {
    _id: "2",
    name: "Veg Salad",
    image: "/food_2.png",
    price: 18,
    description:
      "A vibrant mix of fresh veggies that is both healthy and delicious.",
    category: "Salad",
    flavor: "Crunchy, fresh, slightly sweet",
    servingSize: "1 bowl (approx. 300g)",
    cookingStyle: "Chilled, no-cook",
    ingredients: "Lettuce, Carrots, Cucumbers, Bell peppers, Vinaigrette",
  },
  {
    _id: "3",
    name: "Clover Salad",
    image: "/food_3.png",
    price: 16,
    description: "A flavorful salad with fresh greens and a light dressing.",
    category: "Salad",
    flavor: "Earthy, slightly sweet",
    servingSize: "1 bowl (approx. 300g)",
    cookingStyle: "Chilled, no-cook",
    ingredients: "Mixed greens, Radishes, Carrots, Light vinaigrette",
  },
  {
    _id: "4",
    name: "Chicken Salad",
    image: "/food_4.png",
    price: 24,
    description:
      "A hearty salad with grilled chicken, perfect for a filling meal.",
    category: "Salad",
    flavor: "Savory, slightly smoky",
    servingSize: "1 bowl (approx. 350g)",
    cookingStyle: "Grilled and chilled",
    ingredients:
      "Grilled chicken, Lettuce, Cherry tomatoes, Cucumbers, Ranch dressing",
  },
  {
    _id: "5",
    name: "Lasagna Rolls",
    image: "/food_5.png",
    price: 14,
    description:
      "Savory lasagna rolled with cheese and herbs, baked to perfection.",
    category: "Rolls",
    flavor: "Cheesy, hearty",
    servingSize: "2 rolls (approx. 250g)",
    cookingStyle: "Baked",
    ingredients:
      "Lasagna sheets, Ricotta cheese, Spinach, Tomato sauce, Parmesan",
  },
  {
    _id: "6",
    name: "Peri Peri Rolls",
    image: "/food_6.png",
    price: 12,
    description:
      "Spicy rolls with a peri peri sauce, perfect for spice lovers.",
    category: "Rolls",
    flavor: "Spicy, tangy",
    servingSize: "2 rolls (approx. 200g)",
    cookingStyle: "Baked",
    ingredients: "Tortilla wraps, Peri peri sauce, Chicken, Lettuce, Cheese",
  },
  {
    _id: "7",
    name: "Choco Shake",
    image: "/food_7.png",
    price: 8,
    description:
      "A rich and creamy chocolate shake, perfect for dessert lovers.",
    category: "Beverage",
    flavor: "Sweet, chocolaty",
    servingSize: "1 glass (approx. 300ml)",
    cookingStyle: "Blended",
    ingredients: "Milk, Chocolate syrup, Whipped cream, Ice",
  },
  {
    _id: "8",
    name: "Mango Smoothie",
    image: "/food_8.png",
    price: 10,
    description: "A tropical delight made with fresh mangoes and yogurt.",
    category: "Beverage",
    flavor: "Sweet, fruity",
    servingSize: "1 glass (approx. 300ml)",
    cookingStyle: "Blended",
    ingredients: "Mangoes, Yogurt, Honey, Ice",
  },
  {
    _id: "9",
    name: "Spicy Ramen",
    image: "/food_9.png",
    price: 15,
    description:
      "A bowl of spicy and flavorful ramen, perfect for spice enthusiasts.",
    category: "Noodles",
    flavor: "Spicy, umami",
    servingSize: "1 bowl (approx. 400g)",
    cookingStyle: "Boiled",
    ingredients:
      "Ramen noodles, Spicy broth, Boiled egg, Green onions, Chili paste",
  },
  {
    _id: "10",
    name: "Chicken Biryani",
    image: "/food_10.png",
    price: 20,
    description:
      "A flavorful and aromatic rice dish with tender chicken pieces.",
    category: "Rice",
    flavor: "Spiced, savory",
    servingSize: "1 plate (approx. 500g)",
    cookingStyle: "Cooked and steamed",
    ingredients:
      "Basmati rice, Chicken, Spices, Yogurt, Fried onions, Mint leaves",
  },
];
